package example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Supplier implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String user;
	private double offer;
	private java.util.Date deliveryDate;

	public Supplier() {
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public double getOffer() {
		return this.offer;
	}

	public void setOffer(double offer) {
		this.offer = offer;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Supplier(java.lang.String user, double offer, java.util.Date deliveryDate) {
		this.user = user;
		this.offer = offer;
		this.deliveryDate = deliveryDate;
	}

	@Override
	public String toString() {
		return String.format("Supplier [user=%s, offer=%s, deliveryDate=%s]", user, offer, deliveryDate);
	}
	

}