package model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Supplier implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String user;
	private double offer;
	private java.util.Date deliveryDate;
	private boolean selected;

	public Supplier() {
	}

	@Override
	public String toString() {
		return String.format("Supplier [user=%s, offer=%s, deliveryDate=%s, selected=%s]", user, offer, deliveryDate,
				isSelected());
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public double getOffer() {
		return this.offer;
	}

	public void setOffer(double offer) {
		this.offer = offer;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public boolean getSelected() {
		return selected;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

}